### ISSUE TITLE
tileseq_mut dies with AttributeError: 'Namespace' object has no attribute 'logger_time'

### ISSUE THREAD

**Issue by jweile** [rothlab/tileseq_mutcount#16]
Adrine came across this error when trying to run tileseqMut. It occurred after the alignment jobs were submitted.
```
Traceback (most recent call last):
  File "/home/rothlab/adesouza/anaconda3/envs/py37/bin/tileseq_mut", line 62, in <module>
    main(args, v)
  File "/home/rothlab/adesouza/.local/lib/python3.7/site-packages/TileSeqMut/main.py", line 626, in main
    mc.main()
  File "/home/rothlab/adesouza/.local/lib/python3.7/site-packages/TileSeqMut/main.py", line 370, in main
    sam_dir = self._align_sh_()
  File "/home/rothlab/adesouza/.local/lib/python3.7/site-packages/TileSeqMut/main.py", line 201, in _align_sh_
    finished = cluster.parse_jobs_galen(job_list, self._args.logger_time, self._logging.getLogger("track.jobs"))
AttributeError: 'Namespace' object has no attribute 'logger_time'
```

input parameters: 
```
0.6.940
fastq,/home/rothlab/adesouza/projects/2022vhlassay/fastq
output,/home/rothlab/adesouza/projects/2022vhlassay/
param,/home/rothlab/adesouza/projects/2022vhlassay/VHL_ODD2GFP_postassay22.csv
name,assayODD2postselection
skip_alignment,False
r1,None
r2,None
log_level,info
environment,GALEN
at,8
mt,36
mm,15
c,8
base,33
test,False
rc,False
sr_Override,False
posteriorQC,False
wt_override,False
calibratePhredWT,False
calibratePhredPhix,False
resubmit,False
```

When trying to run the variant-calling manually afterwards (using skip alignments) a similar error occurred:
```
 _______ __         ___
/_ __(_) /__ ___ ___ ___ _/ _ \_______
 / / / / / -_|_-</ -_) _ `/ ___/ __/ _ \
/_/ /_/_/\__/___/\__/\_, /_/ /_/ \___/
           /_/    v1.2.2
2023-01-05_16:15:01 INFO: Running tileseqMave version 1.2.2
2023-01-05_16:15:01 WARNING: Tile 1 includes start codon!!
2023-01-05_16:15:01 WARNING: Region 1 includes start codon!!
2023-01-05_16:15:01 INFO: Writing output to /home/rothlab/adesouza/projects/2022vhlassay/VHL_ODD2GFP_postassay22.json
2023-01-05_16:15:01 INFO: Conversion successful!
TileSeqMut release 0.6.940
parameter sheet in csv format, converting to json
2023-01-05 16:15:01,816 - main.log: INFO Sam files are read from /home/rothlab/adesouza/projects/2022vhlassay/assayODD2postselection_2023-01-05-14-23-01/assayODD2postselection_2023-01-05-16-15-00_mut_count
2023-01-05 16:15:01,816 - main.log: INFO Mutation count sh files are made in /home/rothlab/adesouza/projects/2022vhlassay/assayODD2postselection_2023-01-05-14-23-01/assayODD2postselection_2023-01-05-16-15-00_mut_count/GALEN_jobs
2023-01-05 16:15:01,821 - main.log: INFO Sample wtR1tile1
2023-01-05 16:15:01,821 - main.log: INFO Read1: /home/rothlab/adesouza/projects/2022vhlassay/assayODD2postselection_2023-01-05-14-23-01/sam_files/wtR1tile1_S10_R1_001.sam
2023-01-05 16:15:01,821 - main.log: INFO Read2: /home/rothlab/adesouza/projects/2022vhlassay/assayODD2postselection_2023-01-05-14-23-01/sam_files/wtR1tile1_S10_R2_001.sam
Traceback (most recent call last):
 File "/home/rothlab/adesouza/anaconda3/envs/py37/bin/tileseq_mut", line 62, in <module>
  main(args, v)
 File "/home/rothlab/adesouza/.local/lib/python3.7/site-packages/TileSeqMut/main.py", line 626, in main
  mc.main()
 File "/home/rothlab/adesouza/.local/lib/python3.7/site-packages/TileSeqMut/main.py", line 460, in main
  finished = self._makejobs(sh_output, sam_dir, self._sample_names)
 File "/home/rothlab/adesouza/.local/lib/python3.7/site-packages/TileSeqMut/main.py", line 294, in _makejobs
  job_id = self._submit_mutcount_jobs(sample, sh_output)
 File "/home/rothlab/adesouza/.local/lib/python3.7/site-packages/TileSeqMut/main.py", line 315, in _submit_mutcount_jobs
  cmd = f"tileseq_mut -n {self._args.name} -r1 {self._r1} -r2 {self._r2} -o {self._output} -p" \
AttributeError: 'Namespace' object has no attribute 'logger_time'
```

**Comment by jweile** [comment]
Fixed. Was caused by two conflicting versions of tileseqMut being installed simultaneously.
